export const USER_REQUEST = 'USER_REQUEST';
export const USER_SUCCESS = 'USER_SUCCESS';
export const USER_FAILURE = 'USER_FAILURE';

export const USER_MEDIAS_REQUEST = 'USER_MEDIAS_REQUEST';
export const USER_MEDIAS_SUCCESS = 'USER_MEDIAS_SUCCESS';
export const USER_MEDIAS_FAILURE = 'USER_MEDIAS_FAILURE';

export const USER_FOLLOWERS_REQUEST = 'USER_FOLLOWERS_REQUEST';
export const USER_FOLLOWERS_SUCCESS = 'USER_FOLLOWERS_SUCCESS';
export const USER_FOLLOWERS_FAILURE = 'USER_FOLLOWERS_FAILURE';

export const USER_FOLLOWINGS_REQUEST = 'USER_FOLLOWINGS_REQUEST';
export const USER_FOLLOWINGS_SUCCESS = 'USER_FOLLOWINGS_SUCCESS';
export const USER_FOLLOWINGS_FAILURE = 'USER_FOLLOWINGS_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_USER = 'LOGOUT_USER';
export const ON_LOGIN_FORM_FIELD_CHANGE = 'ON_LOGIN_FORM_FIELD_CHANGE';

export const SET_USER = 'SET_USER';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const ON_REGISTER_FORM_FIELD_CHANGE = 'ON_REGISTER_FORM_FIELD_CHANGE';

export const MEDIA_FAVORITE = 'MEDIA_FAVORITE';
export const MEDIA_DOWNLOAD = 'MEDIA_DOWNLOAD';

export const COMMENTS_REQUEST = 'COMMENTS_REQUEST';
export const COMMENTS_SUCCESS = 'COMMENTS_SUCCESS';
export const COMMENTS_FAILURE = 'COMMENTS_FAILURE';
export const CREATE_COMMENT_REQUEST = 'CREATE_COMMENT_REQUEST';
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const CREATE_COMMENT_FAILURE = 'CREATE_COMMENT_FAILURE';
export const INVALIDATE_COMMENT = 'INVALIDATE_COMMENT';
export const COMMENT_SAVING = 'COMMENT_SAVING';

export const USER_FAVORITES_SUCCESS = 'USER_FAVORITES_SUCCESS';
export const USER_FAVORITES_REQUEST = 'USER_FAVORITES_REQUEST';
export const USER_FAVORITES_FAILURE = 'USER_FAVORITES_FAILURE';

export const MEDIA_FAVORITES_SUCCESS = 'MEDIA_FAVORITES_SUCCESS';
export const MEDIA_FAVORITES_REQUEST = 'MEDIA_FAVORITES_REQUEST';
export const MEDIA_FAVORITES_FAILURE = 'MEDIA_FAVORITES_FAILURE';

export const MEDIA_DOWNLOADS_SUCCESS = 'MEDIA_DOWNLOADS_SUCCESS';
export const MEDIA_DOWNLOADS_REQUEST = 'MEDIA_DOWNLOADS_REQUEST';
export const MEDIA_DOWNLOADS_FAILURE = 'MEDIA_DOWNLOADS_FAILURE';

export const USER_DOWNLOADS_SUCCESS = 'USER_DOWNLOADS_SUCCESS';
export const USER_DOWNLOADS_REQUEST = 'USER_DOWNLOADS_REQUEST';
export const USER_DOWNLOADS_FAILURE = 'USER_DOWNLOADS_FAILURE';

export const MEDIA_SAVE_SUCCESS = 'MEDIA_SAVE_SUCCESS';
export const MEDIA_SAVE_REQUEST = 'MEDIA_SAVE_REQUEST';
export const MEDIA_SAVE_FAILURE = 'MEDIA_SAVE_FAILURE';

export const MEDIAS_SUCCESS = 'MEDIAS_SUCCESS';
export const MEDIAS_REQUEST = 'MEDIAS_REQUEST';
export const MEDIAS_FAILURE = 'MEDIAS_FAILURE';

export const MEDIA_SUCCESS = 'MEDIA_SUCCESS';
export const MEDIA_REQUEST = 'MEDIA_REQUEST';
export const MEDIA_FAILURE = 'MEDIA_FAILURE';
export const SET_CURRENT_MEDIA = 'SET_CURRENT_MEDIA';